services:
  firestore:
    image: gcr.io/google.com/cloudsdktool/google-cloud-cli:emulators
    command:
      - gcloud
      - emulators
      - firestore
      - start
      - --host-port=0.0.0.0:8080
      - --project=demo-news-summarizer
    ports:
      - "8080:8080"

  web:
    build: .
    ports:
      - "3080:3000"
    environment:
      GOOGLE_CLOUD_PROJECT: "demo-news-summarizer"
      FIRESTORE_EMULATOR_HOST: "firestore:8080"
    depends_on:
      - firestore
    restart: unless-stopped
